### ISSUE TITLE
Generated code won't compile in .Net Framework project

### ISSUE THREAD

**Issue by shanet72** [HavenDV/H.Ipc#1]
### Describe the bug

Generated client code from this library will fail to compile with error:

error CS8370: Feature 'nullable reference types' is not available in C# 7.3. Please use language version 8.0 or greater.

Because the code is auto-generated, I can't look at the exact code compiled.  However, from the example documented here:  [https://github.com/HavenDV/H.ProxyFactory/issues/7#issuecomment-1072287342](url) I believe it comes from this line:

```cs
       private global::H.Pipes.IPipeConnection<string>? Connection { get; set; }
```

Can we get this ? removed from the generation, as it is not really necessary, and blocks usage of this great generator in .Net Framework.

I believe this was never caught because the unit tests for this library are only for .Net 6, not .Net Framework.

### Steps to reproduce the bug

Create a sample .Net Framework library with this code and reference the H.* libraries as shown in the documentation:

```cs
    // Client side implementation
    [H.IpcGenerators.IpcClient]
    public partial class ActionServiceClient : IActionService
    {

    }

    public interface IActionService
    {
        void SendText(string text);
        void ShowTrayIcon();
        void HideTrayIcon();
    }
```

### Expected behavior

Code should compile with no error.

### NuGet package version

0.9.11 for H.Ipc.Core and H.Ipc.Generator
2.0.37 for H.Pipes

### Platform

WPF

### IDE

Visual Studio 2022

**Comment by HavenDV** [comment]
In fact, the code will work in .Net Framework if you add this to the .csproj:
```xml
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
```

But yes, We should support the situation when it's not set.

**Comment by HavenDV** [comment]
I also want to note that you have the opportunity to see the generated code
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/3002068/170798449-d3268fe4-7864-4320-9f8e-f9ac6e3e4abd.png">

**Comment by HavenDV** [comment]
For now, I recommend that you upgrade to a newer version of C#, and explore the benefits it brings.
I also added a note to the README file about this:
https://github.com/HavenDV/H.Ipc#notes

**Comment by shanet72** [comment]
Thank you!!  I can confirm this works.  I totally forgot this was a preview feature at one point--never occurred to me I could still turn that on.  I also never knew that you can see the generated code that way...good to know!

Yes, we are definitely looking at upgrading to .Net 6.  Unfortunately, we are decent-sized (600k+ line Xamarin Forms/WPF) application, and need to wait until Maui is released to update  to .Net 6.  While I have started on this work, due to the complexity of this plus other market demands, we're looking at sometime next year before this will be complete.

In the meantime, I have a (stupid) proprietary 32-bit C++ Win32 DLL that we absolutely need to call from our now-64-bit app and I found this solution as potentially being the simplest way to get it working via IPC.  Kudos for coming up with such a nice solution and sharing it!
